### ISSUE TITLE
UnicodeDecodeError 

### ISSUE THREAD

**Issue by mehmetalici** [urosolia/RacingLMPC#7]
Starting PID
Traceback (most recent call last):
  File "/home_net/malici/Downloads/lmpcugo/RacingLMPC/src/main.py", line 107, in <module>
    ClosedLoopDataPID = pickle.load(file_data)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9e in position 2: ordinal not in range(128)

**Comment by urosolia** [comment]
Could you switch to the branch 'devel-ugo' and try to run the file using Python 2.7?

**Comment by mehmetalici** [comment]
It worked! Thanks

Edit: Now I get another error about plotting. Here is the log:

===== Start Plotting
C:\Users\Mehmet\Anaconda3\envs\RacingLMPC-devel-ugo2\lib\site-packages\matplotlib\cbook\deprecation.py:107:
MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses th
e earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, th
is warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instan
ce.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "main.py", line 224, in <module>
    saveGif_xyResults(map, LMPCOpenLoopData, LMPController, 30)
  File "fnc\plot.py", line 373, in saveGif_xyResults
    anim.save('ClosedLoop.gif', dpi=80, writer='imagemagick')
  File "C:\Users\Mehmet\Anaconda3\envs\RacingLMPC-devel-ugo2\lib\site-packages\matplotlib\animation.py", lin
e 1192, in save
    with writer.saving(self._fig, filename, dpi):
  File "C:\Users\Mehmet\Anaconda3\envs\RacingLMPC-devel-ugo2\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\Mehmet\Anaconda3\envs\RacingLMPC-devel-ugo2\lib\site-packages\matplotlib\animation.py", lin
e 237, in saving
    self.setup(fig, outfile, dpi, *args, **kwargs)
  File "C:\Users\Mehmet\Anaconda3\envs\RacingLMPC-devel-ugo2\lib\site-packages\matplotlib\animation.py", lin
e 887, in setup
    raise ValueError("outfile must be *.htm or *.html")
ValueError: outfile must be *.htm or *.html

I think I should install the correct version of matplotlib package. Could you specify that?
