### ISSUE TITLE
AttributeError: 'OSQP' object has no attribute 'constant'

### ISSUE THREAD

**Issue by zjk1234** [urosolia/RacingLMPC#8]
Starting PID
===== PID terminated
Starting MPC
===== MPC terminated
Starting TV-MPC
===== TV-MPC terminated
Starting LMPC
Traceback (most recent call last):
  File "main.py", line 173, in <module>
    LMPCSimulator.Sim(ClosedLoopLMPC, LMPController, LMPCOpenLoopData)
  File "fnc/SysModel.py", line 37, in Sim
    Controller.solve(x[i, :])
  File "fnc/LMPC.py", line 117, in solve
    res_cons, feasible = osqp_solve_qp(sparse.csr_matrix(M), q, sparse.csr_matrix(F), b, sparse.csr_matrix(G), np.add(np.dot(E,x0),L[:,0]))
  File "fnc/LMPC.py", line 426, in osqp_solve_qp
    if res.info.status_val != osqp.constant('OSQP_SOLVED'):
AttributeError: 'OSQP' object has no attribute 'constant'

**Comment by jayraj3** [comment]
Hello zjk1234,

Do you get any solution? I am facing same problem.

Thanks

**Comment by junzengx14** [comment]
`status_val` is actually an integer in the latest OSQP package.
